name: Deploy
on: [workflow_dispatch]
permissions: 
    contents: read
    id-token: write
jobs:
    deploy:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./infrastructure
        steps:
            - name: Azure login
              uses: azure/login@v2
              with:
                client-id: ${{ secrets.AZURE_CLIENT_ID }}
                tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}
            
            - name: Checkout code
              uses: actions/checkout@v4
        
            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v3
              with:
                terraform_version: '1.9.2'
  

            - name: Terraform Init
              id: init
              run: |
               [ "${{ vars.ARM_USE_OIDC }}" == "true" ] && \
                 terraform init -no-color \
                 -backend-config="subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}" \
                 -backend-config="resource_group_name=test-cicd" \
                 -backend-config="storage_account_name=terraformstate" \
                 -backend-config="container_name=tfstate" \
                 -backend-config="key=${{ github.event.repository.name }}/terraform.tfstate" 
              
              env:
               ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
               ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRETS }}

        

