name: Deploy
on: [workflow_dispatch]
permissions: 
    contents: read
    id-token: write
env:
  ARM_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID_DEV }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  ARM_USE_OIDC: ${{ vars.ARM_USE_OIDC }}
jobs:
   terraform_start:
    runs-on: ubuntu-latest
    # steps:
    #     - name: Azure login
    #       uses: azure/login@v2
    #       with:
    #         client-id: ${{ secrets.AZURE_CLIENT_ID }}
    env:
      ARM_SKIP_PROVIDER_REGISTRATION: true
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
    defaults:
        run:
            working-directory: ./infrastructure
    steps:
        - name: Checkout code
          uses: actions/checkout@v4
        
        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v3
          with:
            terraform_version: '1.9.2'

        - name: Terraform Init
          id: init
          run: |
            [ "${{ vars.ARM_USE_OIDC }}" == "true" ] && \
              terraform init -no-color \
              -backend-config="subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID_CICD }}" \
              -backend-config="resource_group_name=test-cicd" \
              -backend-config="storage_account_name=terraformstate" \
              -backend-config="container_name=tfstate" \
              -backend-config="key=${{ github.event.repository.name }}/terraform.tfstate" 
              
          env:
            ARM_CLIENT_ID: ${{ secrets.ARM_DEV_CLIENT_SECRET }}

        # - name: Terraform Plan
        #   id: plan
        #   run: |
        #       export exitcode=0
        #       terraform plan -no-color -out tfplan || existcode=$?
        #       exit $exitcode

